directories %w(lib spec config)

guard_rspec_options = {
  cmd: "bin/rspec",
  title: "Makita",
  failed_mode: :focus,
  all_after_pass: true
}

guard :rspec, guard_rspec_options do
  require "guard/rspec/dsl"
  dsl = Guard::RSpec::Dsl.new(self)
  rspec = dsl.rspec
  watch(rspec.spec_helper) { rspec.spec_dir }
  watch(rspec.spec_support) { rspec.spec_dir }
  watch(rspec.spec_files)
  ruby = dsl.ruby
  dsl.watch_spec_files_for(ruby.lib_files)
end
